### ISSUE TITLE
Python3 issue

### ISSUE THREAD

**Issue by davxy** [ebs-universe/fpv-gcc#5]
Not sure if fpvgcc is supposed to work with Python3.

I'm able to successfully install it using `sudo pip3 install fpvgcc`.

The issues arise when I'm trying to analyze a map:

```
$ fpvgcc ~/devel/TSMTools/skl/skl.map --sar
Traceback (most recent call last):
  File "/usr/local/bin/fpvgcc", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/fpvgcc/cli.py", line 227, in main
    state_machine = process_map_file(args.mapfile, profile=profile)
  File "/usr/local/lib/python3.8/dist-packages/fpvgcc/fpv.py", line 570, in process_map_file
    process_linkermap_line(line, sm)
  File "/usr/local/lib/python3.8/dist-packages/fpvgcc/fpv.py", line 520, in process_linkermap_line
    process_linkermap_section_headings_line(l, sm)
  File "/usr/local/lib/python3.8/dist-packages/fpvgcc/fpv.py", line 341, in process_linkermap_section_headings_line
    newnode = linkermap_get_newnode(name, sm, True)
  File "/usr/local/lib/python3.8/dist-packages/fpvgcc/fpv.py", line 314, in linkermap_get_newnode
    newnodename = objfile.replace('.', '_')
AttributeError: 'NoneType' object has no attribute 'replace'
```

Any suggestion?

**Comment by chintal** [comment]
@davxy It should work with py3. If you are able to share the map file I might be able to try it out and see what the problem is. 

Could you tell me which toolchain generated the mapfile?

**Comment by davxy** [comment]
@chintal I'm using gcc (Debian 9.3.0-8) 9.3.0

I've tried with the most trivial program I can write:

```
int main(int argc, char **argv) 
{
    return 0;
}
```

Build command line: 
`gcc -Wl,-Map=test.map main.c`

Analysis command:
`fpvgcc skl.map --sar`

Same errors as above.
